# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='inventory_service.proto',
  package='ordermgt',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x17inventory_service.proto\x12\x08ordermgt\"\x1b\n\x0bProductType\x12\x0c\n\x04type\x18\x01 \x01(\t\"*\n\x08Quantity\x12\x0e\n\x06\x61mount\x18\x01 \x01(\t\x12\x0e\n\x06metric\x18\x02 \x01(\t\"\x97\x01\n\x0cStockSummary\x12>\n\x0cproductStock\x18\x01 \x03(\x0b\x32(.ordermgt.StockSummary.ProductStockEntry\x1aG\n\x11ProductStockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.ordermgt.Quantity:\x02\x38\x01\x32\x9b\x01\n\x10InventoryService\x12\x41\n\x12GetProductQuantity\x12\x15.ordermgt.ProductType\x1a\x12.ordermgt.Quantity\"\x00\x12\x44\n\x0fGetStockSummary\x12\x15.ordermgt.ProductType\x1a\x16.ordermgt.StockSummary\"\x00(\x01\x62\x06proto3'
)




_PRODUCTTYPE = _descriptor.Descriptor(
  name='ProductType',
  full_name='ordermgt.ProductType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ordermgt.ProductType.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=64,
)


_QUANTITY = _descriptor.Descriptor(
  name='Quantity',
  full_name='ordermgt.Quantity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='ordermgt.Quantity.amount', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metric', full_name='ordermgt.Quantity.metric', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=108,
)


_STOCKSUMMARY_PRODUCTSTOCKENTRY = _descriptor.Descriptor(
  name='ProductStockEntry',
  full_name='ordermgt.StockSummary.ProductStockEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ordermgt.StockSummary.ProductStockEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ordermgt.StockSummary.ProductStockEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=262,
)

_STOCKSUMMARY = _descriptor.Descriptor(
  name='StockSummary',
  full_name='ordermgt.StockSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='productStock', full_name='ordermgt.StockSummary.productStock', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_STOCKSUMMARY_PRODUCTSTOCKENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=262,
)

_STOCKSUMMARY_PRODUCTSTOCKENTRY.fields_by_name['value'].message_type = _QUANTITY
_STOCKSUMMARY_PRODUCTSTOCKENTRY.containing_type = _STOCKSUMMARY
_STOCKSUMMARY.fields_by_name['productStock'].message_type = _STOCKSUMMARY_PRODUCTSTOCKENTRY
DESCRIPTOR.message_types_by_name['ProductType'] = _PRODUCTTYPE
DESCRIPTOR.message_types_by_name['Quantity'] = _QUANTITY
DESCRIPTOR.message_types_by_name['StockSummary'] = _STOCKSUMMARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProductType = _reflection.GeneratedProtocolMessageType('ProductType', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTTYPE,
  '__module__' : 'inventory_service_pb2'
  # @@protoc_insertion_point(class_scope:ordermgt.ProductType)
  })
_sym_db.RegisterMessage(ProductType)

Quantity = _reflection.GeneratedProtocolMessageType('Quantity', (_message.Message,), {
  'DESCRIPTOR' : _QUANTITY,
  '__module__' : 'inventory_service_pb2'
  # @@protoc_insertion_point(class_scope:ordermgt.Quantity)
  })
_sym_db.RegisterMessage(Quantity)

StockSummary = _reflection.GeneratedProtocolMessageType('StockSummary', (_message.Message,), {

  'ProductStockEntry' : _reflection.GeneratedProtocolMessageType('ProductStockEntry', (_message.Message,), {
    'DESCRIPTOR' : _STOCKSUMMARY_PRODUCTSTOCKENTRY,
    '__module__' : 'inventory_service_pb2'
    # @@protoc_insertion_point(class_scope:ordermgt.StockSummary.ProductStockEntry)
    })
  ,
  'DESCRIPTOR' : _STOCKSUMMARY,
  '__module__' : 'inventory_service_pb2'
  # @@protoc_insertion_point(class_scope:ordermgt.StockSummary)
  })
_sym_db.RegisterMessage(StockSummary)
_sym_db.RegisterMessage(StockSummary.ProductStockEntry)


_STOCKSUMMARY_PRODUCTSTOCKENTRY._options = None

_INVENTORYSERVICE = _descriptor.ServiceDescriptor(
  name='InventoryService',
  full_name='ordermgt.InventoryService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=265,
  serialized_end=420,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetProductQuantity',
    full_name='ordermgt.InventoryService.GetProductQuantity',
    index=0,
    containing_service=None,
    input_type=_PRODUCTTYPE,
    output_type=_QUANTITY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetStockSummary',
    full_name='ordermgt.InventoryService.GetStockSummary',
    index=1,
    containing_service=None,
    input_type=_PRODUCTTYPE,
    output_type=_STOCKSUMMARY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INVENTORYSERVICE)

DESCRIPTOR.services_by_name['InventoryService'] = _INVENTORYSERVICE

# @@protoc_insertion_point(module_scope)
